server:
  port: 8000
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: user-management
          uri: lb://USER-MANAGEMENT
          predicates:
            - Path=/api/v1/user-management/**
          filters:
            - RewritePath=/api/v1/user-management/(?<segment>.*), /$\{segment}
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
jwt:
  secret: LH9QZL8upsPBfuDY+Dkb1kT9DZIIUSuA2u4O6Lfi3mkEfeWtETpVTcR/8SMZdJWn/xNTuCQBE6rBvDXgnVmscQ==
