server:
  port: 0

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gp-user-service
  datasource:
    driver-class-name: com.gp.nut
    url: jdbc:mysql://localhost:332/cqrs
    username: gp
    password: 0603
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  config:
    import:
      - classpath:/bootstrap.yml
  mybatis:
    configuration:
      map-underscore-to-camel-case: true
    mapper-locations: mappers/**/*.xml
    type-aliases-package: com.ohgiraffers.userservice.query.dto
