spring:
  application:
    name: location-service
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

server:
  port: 8081

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

# spring:
#   cloud:
#     discovery:
#       enabled: false
