server:
  port: 0

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: location-service  # ⭐ 이 부분만 변경
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql.coffit.xyz:3322/gpdb  # 팀 공통 DB
    username: goodplace
    password: goodplace

  jpa:
    hibernate:
      ddl-auto: update  # ⭐ create → update 권장 (데이터 보존)
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# JWT 설정은 Location Service에서 사용 안할 수도...
# jwt:
#   secret:
#   expiration: 1800000
#   refresh-expiration: 604800000ed: false