server:
  port: 8005
spring:
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: review-service
          uri: lb://REVIEW-SERVICE
          predicates:
            - Path=/goodplace/review-service/**

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql.coffit.xyz:3322/gpdb
    username: goodplace
    password: goodplace

